### ISSUE TITLE
I Need Help...

### ISSUE THREAD

**Issue by Vixima** [mogzol/BrawlBuilder#1]
i got this error message...
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1961
!!      Partition 0 [DATA]: End of data (0x1da550000) behind end of file
!!      (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M ISO
!!      Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45384148 ["HA8E"]: Offset of TICKET (0x1da550000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45394148 ["HA9E"]: Offset of TICKET (0x1db010000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45414248 ["HBAE"]: Offset of TICKET (0x1dbad0000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45424248 ["HBBE"]: Offset of TICKET (0x1dc5b0000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45434248 ["HBCE"]: Offset of TICKET (0x1dd140000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45444248 ["HBDE"]: Offset of TICKET (0x1ddc20000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45454248 ["HBEE"]: Offset of TICKET (0x1de6e0000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45464248 ["HBFE"]: Offset of TICKET (0x1df1e0000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45474248 ["HBGE"]: Offset of TICKET (0x1dfd90000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x45494248 ["HBIE"]: Offset of TICKET (0x1e0940000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x454b4248 ["HBKE"]: Offset of TICKET (0x1e1900000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso
!! wit: ERROR #16 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1950
!!      Partition 0x454c4248 ["HBLE"]: Offset of TICKET (0x1e5000000) behind
!!      end of file (0x118240000): /cygdrive/c/Users/mary/Downloads/Project M
!!      ISO Builder_v1.1.2/Use With The ISO Builder.iso

please help

**Comment by mogzol** [comment]
Can't really help with that, it looks like wit doesn't like your ISO. Wit is a separate application from BrawlBuilder, so there's not much I can do here. The sha1 hash of a valid, clean brawl ISO should be either 0e95949ac585f357e79fcd34b20670b5dca97ac2 or 59432f150bf6b871ab378bb5b28e92005e0862f6.

If your ISO doesn't match either of those, then try a different ISO (by ripping it again, or re-obtaining it in some other definitely not illegal way).

**Comment by Vixima** [comment]
thank you.
