### ISSUE TITLE
I Need Help Again...

### ISSUE THREAD

**Issue by Vixima** [mogzol/BrawlBuilder#2]
I created an project m iso with your iso builder and i worked but when i go into dolphin before i choose the iso it shows this http://imgur.com/x8UgNFT so i ignore it and start the iso, it opens and then says 

> Your GCM/ISO file seems to be invalid (invalid country).
> Continue with PAL region?

 and if i click yes it starts up like normal but when it goes past the part where it says project m's website link it crashes...

**Comment by mogzol** [comment]
What mod are you trying to build? Unmodified Project M 3.6, or something else?

**Comment by Vixima** [comment]
Modified Project M 3.6

**Comment by mogzol** [comment]
Any more details than that? is it someone's modpack or your own changes?

**Comment by Vixima** [comment]
Just some random mods. examples: frisk texture over lucas, geno over rob, hatsune miku over zss and steve from minecraft over toon link.

**Comment by mogzol** [comment]
Hmm, did you make any changes to the GCT file? Other than that, I'm not sure why it wouldn't work. Try building it without changing the title or ID and see if you still have the problem

**Comment by Vixima** [comment]
No, i didnt change the GCT file, but i am going to try building it without changing the title or ID. thank you!

**Comment by Vixima** [comment]
And it crashed again. but this time it had no invalid country

**Comment by Vixima** [comment]
i just tried rebuilding the iso with the subspace emissary and got this error message.

> Wit closed unexpectedly with exit code 33, stopping build...
> 
> Wit error messages:
> 
> !! wit: ERROR #33 [WRITE FILE FAILED] in SetSizeSF() @ src/lib-sf.c#1767
> !!      Set file size failed [F=3,8022294528]: /cygdrive/n/.Project
> !!      M.iso.gjRXKe.tmp
> !!      -> No space left on device [28]
> !! wit: ERROR #33 [WRITE FILE FAILED] in WriteISO() @ src/lib-sf.c#1684
> !!      Write failed [F=3,4294934528+32768]: /cygdrive/n/.Project
> !!      M.iso.gjRXKe.tmp
> !!      -> No space left on device [28]
> wit: Command 'COPY' returns with status #33 [WRITE FILE FAILED]

**Comment by mogzol** [comment]
Sorry for the slow response. Judging by the "No space left on device" message, I'd say you are probably out of space on whatever drive you are building the ISO on. Note that if you are building the ISO on the same drive that BrawlBuilder is in, you'll need about 15 or 16GB free, since all the brawl files are extracted (~8GB, deleted after the build) and then built into the ISO (another ~8GB).

As for your build crashing, I really don't know. If you can build vanilla P:M fine then its got to be one of your changes causing an issue with BrawlBuilder. If you ever figure out what was causing it then please let me know, I'll see if there's anything I can do to fix it.

**Comment by Vixima** [comment]
btw i was building the iso onto my usb and the usb had 36 gigabytes left and 36 gigabytes is the max space on the usb, so tried it on my hard drive and it worked but it crashed...

**Comment by D4rkMoon** [comment]
Now, can u guys help me?
I got exit error code 31...
Wit closed unexpectedly with exit code 31, stopping build...

Wit error messages:

!! wit: ERROR #31 [READ FILE FAILED] in ReadWBFS() @ src/lib-sf.c#1854
!!      Read failed [S=0,4293591040+1376256]:
!!      /cygdrive/c/Users/Carmen/Desktop/RSBP01.wbfs/#0
!!      -> No such file or directory [2]
!! wit: ERROR #31 [READ FILE FAILED] in wd_read_raw() @ src/libwbfs/wiidisc.c#673
!!      Error while reading disc:
!!      /cygdrive/c/Users/Carmen/Desktop/RSBP01.wbfs/#0
!! wit: ERROR #31 [READ FILE FAILED] in wd_read_raw() @ src/libwbfs/wiidisc.c#673
!!      Error while reading disc:
!!      /cygdrive/c/Users/Carmen/Desktop/RSBP01.wbfs/#0
wit: Command 'EXTRACT' returns with status #31 [READ FILE FAILED]
can u help me?

**Comment by D4rkMn** [comment]
can u guys help m now?
i got dis:
Wit closed unexpectedly with exit code 31, stopping build...

Wit error messages:

!! wit: ERROR #31 [READ FILE FAILED] in ReadWBFS() @ src/lib-sf.c#1854
!!      Read failed [S=0,4293591040+1376256]:
!!      /cygdrive/c/Users/Computer/Desktop/RSBP01.wbfs/#0
!!      -> No such file or directory [2]
!! wit: ERROR #31 [READ FILE FAILED] in wd_read_raw() @ src/libwbfs/wiidisc.c#673
!!      Error while reading disc:
!!      /cygdrive/c/Users/Computer/Desktop/RSBP01.wbfs/#0
!! wit: ERROR #31 [READ FILE FAILED] in wd_read_raw() @ src/libwbfs/wiidisc.c#673
!!      Error while reading disc:
!!      /cygdrive/c/Users/Computer/Desktop/RSBP01.wbfs/#0
wit: Command 'EXTRACT' returns with status #31 [READ FILE FAILED]
help pls D:
